//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Zus3.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageIndex", Namespace="naws.zus.pl")]
    [System.SerializableAttribute()]
    public partial class MessageIndex : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Zus3.ServiceReference1.MessageIndexElement[] m_collectionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public Zus3.ServiceReference1.MessageIndexElement[] m_collection {
            get {
                return this.m_collectionField;
            }
            set {
                if ((object.ReferenceEquals(this.m_collectionField, value) != true)) {
                    this.m_collectionField = value;
                    this.RaisePropertyChanged("m_collection");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MessageIndexElement", Namespace="naws.zus.pl")]
    [System.SerializableAttribute()]
    public partial class MessageIndexElement : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strIdentyfikatorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strIdZadaniaField;
        
        private System.DateTime DataWpisuField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strTypField;
        
        private int uiWielkoscPrzesylkiField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string strB64HashField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string strIdentyfikator {
            get {
                return this.strIdentyfikatorField;
            }
            set {
                if ((object.ReferenceEquals(this.strIdentyfikatorField, value) != true)) {
                    this.strIdentyfikatorField = value;
                    this.RaisePropertyChanged("strIdentyfikator");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strIdZadania {
            get {
                return this.strIdZadaniaField;
            }
            set {
                if ((object.ReferenceEquals(this.strIdZadaniaField, value) != true)) {
                    this.strIdZadaniaField = value;
                    this.RaisePropertyChanged("strIdZadania");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=2)]
        public System.DateTime DataWpisu {
            get {
                return this.DataWpisuField;
            }
            set {
                if ((this.DataWpisuField.Equals(value) != true)) {
                    this.DataWpisuField = value;
                    this.RaisePropertyChanged("DataWpisu");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strTyp {
            get {
                return this.strTypField;
            }
            set {
                if ((object.ReferenceEquals(this.strTypField, value) != true)) {
                    this.strTypField = value;
                    this.RaisePropertyChanged("strTyp");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public int uiWielkoscPrzesylki {
            get {
                return this.uiWielkoscPrzesylkiField;
            }
            set {
                if ((this.uiWielkoscPrzesylkiField.Equals(value) != true)) {
                    this.uiWielkoscPrzesylkiField = value;
                    this.RaisePropertyChanged("uiWielkoscPrzesylki");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strB64Hash {
            get {
                return this.strB64HashField;
            }
            set {
                if ((object.ReferenceEquals(this.strB64HashField, value) != true)) {
                    this.strB64HashField = value;
                    this.RaisePropertyChanged("strB64Hash");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="naws.zus.pl", ConfigurationName="ServiceReference1.INawsUslugi")]
    public interface INawsUslugi {
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/WyslijPrzesylke", ReplyAction="naws.zus.pl/WyslijPrzesylkeResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="naws.zus.pl/INawsUslugi/WyslijPrzesylkeExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Zus3.ServiceReference1.WyslijPrzesylkeResponse WyslijPrzesylke(Zus3.ServiceReference1.WyslijPrzesylkeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/WyslijPrzesylke", ReplyAction="naws.zus.pl/WyslijPrzesylkeResponse")]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.WyslijPrzesylkeResponse> WyslijPrzesylkeAsync(Zus3.ServiceReference1.WyslijPrzesylkeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/CheckTransmision", ReplyAction="naws.zus.pl/CheckTransmisionResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="naws.zus.pl/INawsUslugi/CheckTransmisionExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Zus3.ServiceReference1.CheckTransmisionResponse CheckTransmision(Zus3.ServiceReference1.CheckTransmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/CheckTransmision", ReplyAction="naws.zus.pl/CheckTransmisionResponse")]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.CheckTransmisionResponse> CheckTransmisionAsync(Zus3.ServiceReference1.CheckTransmisionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/PobierzPotwierdzenie", ReplyAction="naws.zus.pl/PobierzPotwierdzenieResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="naws.zus.pl/INawsUslugi/PobierzPotwierdzenieExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Zus3.ServiceReference1.PobierzPotwierdzenieResponse PobierzPotwierdzenie(Zus3.ServiceReference1.PobierzPotwierdzenieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/PobierzPotwierdzenie", ReplyAction="naws.zus.pl/PobierzPotwierdzenieResponse")]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.PobierzPotwierdzenieResponse> PobierzPotwierdzenieAsync(Zus3.ServiceReference1.PobierzPotwierdzenieRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/PobierzIndexPrzesylek", ReplyAction="naws.zus.pl/PobierzIndexPrzesylekResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(System.Exception), Action="naws.zus.pl/INawsUslugi/PobierzIndexPrzesylekExceptionFault", Name="Exception", Namespace="http://schemas.datacontract.org/2004/07/System")]
        Zus3.ServiceReference1.PobierzIndexPrzesylekResponse PobierzIndexPrzesylek(Zus3.ServiceReference1.PobierzIndexPrzesylekRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="naws.zus.pl/PobierzIndexPrzesylek", ReplyAction="naws.zus.pl/PobierzIndexPrzesylekResponse")]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.PobierzIndexPrzesylekResponse> PobierzIndexPrzesylekAsync(Zus3.ServiceReference1.PobierzIndexPrzesylekRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WyslijPrzesylkeRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WyslijPrzesylke", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.WyslijPrzesylkeRequestBody Body;
        
        public WyslijPrzesylkeRequest() {
        }
        
        public WyslijPrzesylkeRequest(Zus3.ServiceReference1.WyslijPrzesylkeRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class WyslijPrzesylkeRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] pbyPrzesylka;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint uiPrzesylkaDlugosc;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNazwaProducenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strNazwaOprogramowania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strWersjaOprogramowania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strB64SkrotPrzesylkiIn;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strTypPrzesylki;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public System.Nullable<int> metodaPodpisu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public string strB64SkrotPrzesylkiOut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strIdentyfikator;
        
        public WyslijPrzesylkeRequestBody() {
        }
        
        public WyslijPrzesylkeRequestBody(byte[] pbyPrzesylka, uint uiPrzesylkaDlugosc, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, string strB64SkrotPrzesylkiIn, string strTypPrzesylki, System.Nullable<int> metodaPodpisu, string strB64SkrotPrzesylkiOut, string strIdentyfikator) {
            this.pbyPrzesylka = pbyPrzesylka;
            this.uiPrzesylkaDlugosc = uiPrzesylkaDlugosc;
            this.strNazwaProducenta = strNazwaProducenta;
            this.strNazwaOprogramowania = strNazwaOprogramowania;
            this.strWersjaOprogramowania = strWersjaOprogramowania;
            this.strB64SkrotPrzesylkiIn = strB64SkrotPrzesylkiIn;
            this.strTypPrzesylki = strTypPrzesylki;
            this.metodaPodpisu = metodaPodpisu;
            this.strB64SkrotPrzesylkiOut = strB64SkrotPrzesylkiOut;
            this.strIdentyfikator = strIdentyfikator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WyslijPrzesylkeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WyslijPrzesylkeResponse", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.WyslijPrzesylkeResponseBody Body;
        
        public WyslijPrzesylkeResponse() {
        }
        
        public WyslijPrzesylkeResponse(Zus3.ServiceReference1.WyslijPrzesylkeResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class WyslijPrzesylkeResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strB64SkrotPrzesylkiOut;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strIdentyfikator;
        
        public WyslijPrzesylkeResponseBody() {
        }
        
        public WyslijPrzesylkeResponseBody(string strB64SkrotPrzesylkiOut, string strIdentyfikator) {
            this.strB64SkrotPrzesylkiOut = strB64SkrotPrzesylkiOut;
            this.strIdentyfikator = strIdentyfikator;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransmisionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransmision", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.CheckTransmisionRequestBody Body;
        
        public CheckTransmisionRequest() {
        }
        
        public CheckTransmisionRequest(Zus3.ServiceReference1.CheckTransmisionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class CheckTransmisionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] byDataIn;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint uiDataInLength;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public byte[] byDataOut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public uint uiDataOutLength;
        
        public CheckTransmisionRequestBody() {
        }
        
        public CheckTransmisionRequestBody(byte[] byDataIn, uint uiDataInLength, byte[] byDataOut, uint uiDataOutLength) {
            this.byDataIn = byDataIn;
            this.uiDataInLength = uiDataInLength;
            this.byDataOut = byDataOut;
            this.uiDataOutLength = uiDataOutLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CheckTransmisionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CheckTransmisionResponse", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.CheckTransmisionResponseBody Body;
        
        public CheckTransmisionResponse() {
        }
        
        public CheckTransmisionResponse(Zus3.ServiceReference1.CheckTransmisionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class CheckTransmisionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public byte[] byDataOut;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public uint uiDataOutLength;
        
        public CheckTransmisionResponseBody() {
        }
        
        public CheckTransmisionResponseBody(byte[] byDataOut, uint uiDataOutLength) {
            this.byDataOut = byDataOut;
            this.uiDataOutLength = uiDataOutLength;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzPotwierdzenieRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzPotwierdzenie", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.PobierzPotwierdzenieRequestBody Body;
        
        public PobierzPotwierdzenieRequest() {
        }
        
        public PobierzPotwierdzenieRequest(Zus3.ServiceReference1.PobierzPotwierdzenieRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class PobierzPotwierdzenieRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strIdentyfikator;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strNazwaProducenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNazwaOprogramowania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strWersjaOprogramowania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string strIdZadania;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public System.DateTime DataWpisu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public string strTyp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public uint uiWielkoscPrzesylki;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=8)]
        public byte[] byPrzesylka;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=9)]
        public string strB64Skrot;
        
        public PobierzPotwierdzenieRequestBody() {
        }
        
        public PobierzPotwierdzenieRequestBody(string strIdentyfikator, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, string strIdZadania, System.DateTime DataWpisu, string strTyp, uint uiWielkoscPrzesylki, byte[] byPrzesylka, string strB64Skrot) {
            this.strIdentyfikator = strIdentyfikator;
            this.strNazwaProducenta = strNazwaProducenta;
            this.strNazwaOprogramowania = strNazwaOprogramowania;
            this.strWersjaOprogramowania = strWersjaOprogramowania;
            this.strIdZadania = strIdZadania;
            this.DataWpisu = DataWpisu;
            this.strTyp = strTyp;
            this.uiWielkoscPrzesylki = uiWielkoscPrzesylki;
            this.byPrzesylka = byPrzesylka;
            this.strB64Skrot = strB64Skrot;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzPotwierdzenieResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzPotwierdzenieResponse", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.PobierzPotwierdzenieResponseBody Body;
        
        public PobierzPotwierdzenieResponse() {
        }
        
        public PobierzPotwierdzenieResponse(Zus3.ServiceReference1.PobierzPotwierdzenieResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class PobierzPotwierdzenieResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strIdZadania;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public System.DateTime DataWpisu;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strTyp;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public uint uiWielkoscPrzesylki;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public byte[] byPrzesylka;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string strB64Skrot;
        
        public PobierzPotwierdzenieResponseBody() {
        }
        
        public PobierzPotwierdzenieResponseBody(string strIdZadania, System.DateTime DataWpisu, string strTyp, uint uiWielkoscPrzesylki, byte[] byPrzesylka, string strB64Skrot) {
            this.strIdZadania = strIdZadania;
            this.DataWpisu = DataWpisu;
            this.strTyp = strTyp;
            this.uiWielkoscPrzesylki = uiWielkoscPrzesylki;
            this.byPrzesylka = byPrzesylka;
            this.strB64Skrot = strB64Skrot;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzIndexPrzesylekRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzIndexPrzesylek", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.PobierzIndexPrzesylekRequestBody Body;
        
        public PobierzIndexPrzesylekRequest() {
        }
        
        public PobierzIndexPrzesylekRequest(Zus3.ServiceReference1.PobierzIndexPrzesylekRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class PobierzIndexPrzesylekRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string strIdZadania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string strNazwaProducenta;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string strNazwaOprogramowania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string strWersjaOprogramowania;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public Zus3.ServiceReference1.MessageIndex msgIndex;
        
        public PobierzIndexPrzesylekRequestBody() {
        }
        
        public PobierzIndexPrzesylekRequestBody(string strIdZadania, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, Zus3.ServiceReference1.MessageIndex msgIndex) {
            this.strIdZadania = strIdZadania;
            this.strNazwaProducenta = strNazwaProducenta;
            this.strNazwaOprogramowania = strNazwaOprogramowania;
            this.strWersjaOprogramowania = strWersjaOprogramowania;
            this.msgIndex = msgIndex;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class PobierzIndexPrzesylekResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="PobierzIndexPrzesylekResponse", Namespace="naws.zus.pl", Order=0)]
        public Zus3.ServiceReference1.PobierzIndexPrzesylekResponseBody Body;
        
        public PobierzIndexPrzesylekResponse() {
        }
        
        public PobierzIndexPrzesylekResponse(Zus3.ServiceReference1.PobierzIndexPrzesylekResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="naws.zus.pl")]
    public partial class PobierzIndexPrzesylekResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public Zus3.ServiceReference1.MessageIndex msgIndex;
        
        public PobierzIndexPrzesylekResponseBody() {
        }
        
        public PobierzIndexPrzesylekResponseBody(Zus3.ServiceReference1.MessageIndex msgIndex) {
            this.msgIndex = msgIndex;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface INawsUslugiChannel : Zus3.ServiceReference1.INawsUslugi, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NawsUslugiClient : System.ServiceModel.ClientBase<Zus3.ServiceReference1.INawsUslugi>, Zus3.ServiceReference1.INawsUslugi {
        
        public NawsUslugiClient() {
        }
        
        public NawsUslugiClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NawsUslugiClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NawsUslugiClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NawsUslugiClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zus3.ServiceReference1.WyslijPrzesylkeResponse Zus3.ServiceReference1.INawsUslugi.WyslijPrzesylke(Zus3.ServiceReference1.WyslijPrzesylkeRequest request) {
            return base.Channel.WyslijPrzesylke(request);
        }
        
        public void WyslijPrzesylke(byte[] pbyPrzesylka, uint uiPrzesylkaDlugosc, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, string strB64SkrotPrzesylkiIn, string strTypPrzesylki, System.Nullable<int> metodaPodpisu, ref string strB64SkrotPrzesylkiOut, ref string strIdentyfikator) {
            Zus3.ServiceReference1.WyslijPrzesylkeRequest inValue = new Zus3.ServiceReference1.WyslijPrzesylkeRequest();
            inValue.Body = new Zus3.ServiceReference1.WyslijPrzesylkeRequestBody();
            inValue.Body.pbyPrzesylka = pbyPrzesylka;
            inValue.Body.uiPrzesylkaDlugosc = uiPrzesylkaDlugosc;
            inValue.Body.strNazwaProducenta = strNazwaProducenta;
            inValue.Body.strNazwaOprogramowania = strNazwaOprogramowania;
            inValue.Body.strWersjaOprogramowania = strWersjaOprogramowania;
            inValue.Body.strB64SkrotPrzesylkiIn = strB64SkrotPrzesylkiIn;
            inValue.Body.strTypPrzesylki = strTypPrzesylki;
            inValue.Body.metodaPodpisu = metodaPodpisu;
            inValue.Body.strB64SkrotPrzesylkiOut = strB64SkrotPrzesylkiOut;
            inValue.Body.strIdentyfikator = strIdentyfikator;
            Zus3.ServiceReference1.WyslijPrzesylkeResponse retVal = ((Zus3.ServiceReference1.INawsUslugi)(this)).WyslijPrzesylke(inValue);
            strB64SkrotPrzesylkiOut = retVal.Body.strB64SkrotPrzesylkiOut;
            strIdentyfikator = retVal.Body.strIdentyfikator;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.WyslijPrzesylkeResponse> Zus3.ServiceReference1.INawsUslugi.WyslijPrzesylkeAsync(Zus3.ServiceReference1.WyslijPrzesylkeRequest request) {
            return base.Channel.WyslijPrzesylkeAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zus3.ServiceReference1.WyslijPrzesylkeResponse> WyslijPrzesylkeAsync(byte[] pbyPrzesylka, uint uiPrzesylkaDlugosc, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, string strB64SkrotPrzesylkiIn, string strTypPrzesylki, System.Nullable<int> metodaPodpisu, string strB64SkrotPrzesylkiOut, string strIdentyfikator) {
            Zus3.ServiceReference1.WyslijPrzesylkeRequest inValue = new Zus3.ServiceReference1.WyslijPrzesylkeRequest();
            inValue.Body = new Zus3.ServiceReference1.WyslijPrzesylkeRequestBody();
            inValue.Body.pbyPrzesylka = pbyPrzesylka;
            inValue.Body.uiPrzesylkaDlugosc = uiPrzesylkaDlugosc;
            inValue.Body.strNazwaProducenta = strNazwaProducenta;
            inValue.Body.strNazwaOprogramowania = strNazwaOprogramowania;
            inValue.Body.strWersjaOprogramowania = strWersjaOprogramowania;
            inValue.Body.strB64SkrotPrzesylkiIn = strB64SkrotPrzesylkiIn;
            inValue.Body.strTypPrzesylki = strTypPrzesylki;
            inValue.Body.metodaPodpisu = metodaPodpisu;
            inValue.Body.strB64SkrotPrzesylkiOut = strB64SkrotPrzesylkiOut;
            inValue.Body.strIdentyfikator = strIdentyfikator;
            return ((Zus3.ServiceReference1.INawsUslugi)(this)).WyslijPrzesylkeAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zus3.ServiceReference1.CheckTransmisionResponse Zus3.ServiceReference1.INawsUslugi.CheckTransmision(Zus3.ServiceReference1.CheckTransmisionRequest request) {
            return base.Channel.CheckTransmision(request);
        }
        
        public void CheckTransmision(byte[] byDataIn, uint uiDataInLength, ref byte[] byDataOut, ref uint uiDataOutLength) {
            Zus3.ServiceReference1.CheckTransmisionRequest inValue = new Zus3.ServiceReference1.CheckTransmisionRequest();
            inValue.Body = new Zus3.ServiceReference1.CheckTransmisionRequestBody();
            inValue.Body.byDataIn = byDataIn;
            inValue.Body.uiDataInLength = uiDataInLength;
            inValue.Body.byDataOut = byDataOut;
            inValue.Body.uiDataOutLength = uiDataOutLength;
            Zus3.ServiceReference1.CheckTransmisionResponse retVal = ((Zus3.ServiceReference1.INawsUslugi)(this)).CheckTransmision(inValue);
            byDataOut = retVal.Body.byDataOut;
            uiDataOutLength = retVal.Body.uiDataOutLength;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.CheckTransmisionResponse> Zus3.ServiceReference1.INawsUslugi.CheckTransmisionAsync(Zus3.ServiceReference1.CheckTransmisionRequest request) {
            return base.Channel.CheckTransmisionAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zus3.ServiceReference1.CheckTransmisionResponse> CheckTransmisionAsync(byte[] byDataIn, uint uiDataInLength, byte[] byDataOut, uint uiDataOutLength) {
            Zus3.ServiceReference1.CheckTransmisionRequest inValue = new Zus3.ServiceReference1.CheckTransmisionRequest();
            inValue.Body = new Zus3.ServiceReference1.CheckTransmisionRequestBody();
            inValue.Body.byDataIn = byDataIn;
            inValue.Body.uiDataInLength = uiDataInLength;
            inValue.Body.byDataOut = byDataOut;
            inValue.Body.uiDataOutLength = uiDataOutLength;
            return ((Zus3.ServiceReference1.INawsUslugi)(this)).CheckTransmisionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zus3.ServiceReference1.PobierzPotwierdzenieResponse Zus3.ServiceReference1.INawsUslugi.PobierzPotwierdzenie(Zus3.ServiceReference1.PobierzPotwierdzenieRequest request) {
            return base.Channel.PobierzPotwierdzenie(request);
        }
        
        public void PobierzPotwierdzenie(string strIdentyfikator, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, ref string strIdZadania, ref System.DateTime DataWpisu, ref string strTyp, ref uint uiWielkoscPrzesylki, ref byte[] byPrzesylka, ref string strB64Skrot) {
            Zus3.ServiceReference1.PobierzPotwierdzenieRequest inValue = new Zus3.ServiceReference1.PobierzPotwierdzenieRequest();
            inValue.Body = new Zus3.ServiceReference1.PobierzPotwierdzenieRequestBody();
            inValue.Body.strIdentyfikator = strIdentyfikator;
            inValue.Body.strNazwaProducenta = strNazwaProducenta;
            inValue.Body.strNazwaOprogramowania = strNazwaOprogramowania;
            inValue.Body.strWersjaOprogramowania = strWersjaOprogramowania;
            inValue.Body.strIdZadania = strIdZadania;
            inValue.Body.DataWpisu = DataWpisu;
            inValue.Body.strTyp = strTyp;
            inValue.Body.uiWielkoscPrzesylki = uiWielkoscPrzesylki;
            inValue.Body.byPrzesylka = byPrzesylka;
            inValue.Body.strB64Skrot = strB64Skrot;
            Zus3.ServiceReference1.PobierzPotwierdzenieResponse retVal = ((Zus3.ServiceReference1.INawsUslugi)(this)).PobierzPotwierdzenie(inValue);
            strIdZadania = retVal.Body.strIdZadania;
            DataWpisu = retVal.Body.DataWpisu;
            strTyp = retVal.Body.strTyp;
            uiWielkoscPrzesylki = retVal.Body.uiWielkoscPrzesylki;
            byPrzesylka = retVal.Body.byPrzesylka;
            strB64Skrot = retVal.Body.strB64Skrot;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.PobierzPotwierdzenieResponse> Zus3.ServiceReference1.INawsUslugi.PobierzPotwierdzenieAsync(Zus3.ServiceReference1.PobierzPotwierdzenieRequest request) {
            return base.Channel.PobierzPotwierdzenieAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zus3.ServiceReference1.PobierzPotwierdzenieResponse> PobierzPotwierdzenieAsync(string strIdentyfikator, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, string strIdZadania, System.DateTime DataWpisu, string strTyp, uint uiWielkoscPrzesylki, byte[] byPrzesylka, string strB64Skrot) {
            Zus3.ServiceReference1.PobierzPotwierdzenieRequest inValue = new Zus3.ServiceReference1.PobierzPotwierdzenieRequest();
            inValue.Body = new Zus3.ServiceReference1.PobierzPotwierdzenieRequestBody();
            inValue.Body.strIdentyfikator = strIdentyfikator;
            inValue.Body.strNazwaProducenta = strNazwaProducenta;
            inValue.Body.strNazwaOprogramowania = strNazwaOprogramowania;
            inValue.Body.strWersjaOprogramowania = strWersjaOprogramowania;
            inValue.Body.strIdZadania = strIdZadania;
            inValue.Body.DataWpisu = DataWpisu;
            inValue.Body.strTyp = strTyp;
            inValue.Body.uiWielkoscPrzesylki = uiWielkoscPrzesylki;
            inValue.Body.byPrzesylka = byPrzesylka;
            inValue.Body.strB64Skrot = strB64Skrot;
            return ((Zus3.ServiceReference1.INawsUslugi)(this)).PobierzPotwierdzenieAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Zus3.ServiceReference1.PobierzIndexPrzesylekResponse Zus3.ServiceReference1.INawsUslugi.PobierzIndexPrzesylek(Zus3.ServiceReference1.PobierzIndexPrzesylekRequest request) {
            return base.Channel.PobierzIndexPrzesylek(request);
        }
        
        public void PobierzIndexPrzesylek(string strIdZadania, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, ref Zus3.ServiceReference1.MessageIndex msgIndex) {
            Zus3.ServiceReference1.PobierzIndexPrzesylekRequest inValue = new Zus3.ServiceReference1.PobierzIndexPrzesylekRequest();
            inValue.Body = new Zus3.ServiceReference1.PobierzIndexPrzesylekRequestBody();
            inValue.Body.strIdZadania = strIdZadania;
            inValue.Body.strNazwaProducenta = strNazwaProducenta;
            inValue.Body.strNazwaOprogramowania = strNazwaOprogramowania;
            inValue.Body.strWersjaOprogramowania = strWersjaOprogramowania;
            inValue.Body.msgIndex = msgIndex;
            Zus3.ServiceReference1.PobierzIndexPrzesylekResponse retVal = ((Zus3.ServiceReference1.INawsUslugi)(this)).PobierzIndexPrzesylek(inValue);
            msgIndex = retVal.Body.msgIndex;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Zus3.ServiceReference1.PobierzIndexPrzesylekResponse> Zus3.ServiceReference1.INawsUslugi.PobierzIndexPrzesylekAsync(Zus3.ServiceReference1.PobierzIndexPrzesylekRequest request) {
            return base.Channel.PobierzIndexPrzesylekAsync(request);
        }
        
        public System.Threading.Tasks.Task<Zus3.ServiceReference1.PobierzIndexPrzesylekResponse> PobierzIndexPrzesylekAsync(string strIdZadania, string strNazwaProducenta, string strNazwaOprogramowania, string strWersjaOprogramowania, Zus3.ServiceReference1.MessageIndex msgIndex) {
            Zus3.ServiceReference1.PobierzIndexPrzesylekRequest inValue = new Zus3.ServiceReference1.PobierzIndexPrzesylekRequest();
            inValue.Body = new Zus3.ServiceReference1.PobierzIndexPrzesylekRequestBody();
            inValue.Body.strIdZadania = strIdZadania;
            inValue.Body.strNazwaProducenta = strNazwaProducenta;
            inValue.Body.strNazwaOprogramowania = strNazwaOprogramowania;
            inValue.Body.strWersjaOprogramowania = strWersjaOprogramowania;
            inValue.Body.msgIndex = msgIndex;
            return ((Zus3.ServiceReference1.INawsUslugi)(this)).PobierzIndexPrzesylekAsync(inValue);
        }
    }
}
